### ISSUE TITLE
Implement Planets Routes and Logic

### ISSUE THREAD

**Issue by Tarskan** [cybe-m1/Blueplanet_Anatole_de_Chauveron_Tristan_Six#10]
Implement all routes and logic for Planets.

## Tasks

- [ ] Create a new Planets
- [ ] Update an existing Planets
- [ ] Delete an Planets
- [ ] Fetch an Planets
- [ ] Fetch list of Planets:
  - [ ] According to Planets
  - [ ] According to number
  - [ ] According to specific characteristic

:rocket: Planets milestone will already be implemented.
