### ISSUE TITLE
Implement Animals Routes and Logic

### ISSUE THREAD

**Issue by Anatole-DC** [cybe-m1/Blueplanet_Anatole_de_Chauveron_Tristan_Six#2]
Implement all routes and logic for Animals.

## Tasks

- [ ] Create a new Animal
- [ ] Update an existing animal
- [ ] Delete an animal
- [ ] Fetch an animal
- [ ] Fetch list of animal :
  - [ ] According to names
  - [ ] According to number
  - [ ] According to place
  - [ ] According to specific characteristic

:rocket: Planet milestone will already be implemented.
