### ISSUE TITLE
Implement Animal testing

### ISSUE THREAD

**Issue by Anatole-DC** [cybe-m1/Blueplanet_Anatole_de_Chauveron_Tristan_Six#3]
Implement all animal tests and failing tests.

## Tasks

- [ ] CRUD tests :
  - [ ] Create
    - [ ] Created 
    - [ ] Fail if animal already exists
  - [ ] Recover
    - [ ] Recover
    - [ ] Fail if animal does not exist
  - [ ] Update
    - [ ] Recover
    - [ ] Fail if animal does not exist
  - [ ] Delete
    - [ ] Recover
    - [ ] Fail if animal does not exist

:rocket: All tests will be able to be ran in a github action for this project, in order to have an insanly good project.
