### ISSUE TITLE
Implement Planet testing

### ISSUE THREAD

**Issue by Tarskan** [cybe-m1/Blueplanet_Anatole_de_Chauveron_Tristan_Six#7]
Implement all planet tests and failing tests.

## Tasks

- [ ] CRUD tests :
  - [ ] Create
    - [ ] Created 
    - [ ] Fail if planet already exists
  - [ ] Recover
    - [ ] Recover
    - [ ] Fail if planet does not exist
  - [ ] Update
    - [ ] Recover
    - [ ] Fail if planet does not exist
  - [ ] Delete
    - [ ] Recover
    - [ ] Fail if planet does not exist

:rocket: All tests will be able to be ran in a github action for this project, in order to have an insanly good project.
