### ISSUE TITLE
Implement 

### ISSUE THREAD

**Issue by Tarskan** [cybe-m1/Blueplanet_Anatole_de_Chauveron_Tristan_Six#8]
Implement all user tests and failing tests.

## Tasks

- [ ] CRUD tests :
  - [ ] Create
    - [ ] Created 
    - [ ] Fail if user already exists
  - [ ] Recover
    - [ ] Recover
    - [ ] Fail if user does not exist
  - [ ] Update
    - [ ] Recover
    - [ ] Fail if user does not exist
  - [ ] Delete
    - [ ] Recover
    - [ ] Fail if user does not exist

:rocket: All tests will be able to be ran in a github action for this project, in order to have an insanly good project.
