### ISSUE TITLE
Implement User Routes and Logic

### ISSUE THREAD

**Issue by Tarskan** [cybe-m1/Blueplanet_Anatole_de_Chauveron_Tristan_Six#9]
Implement all routes and logic for Animals.

## Tasks

- [ ] Create a new User
- [ ] Update an existing User
- [ ] Delete an User
- [ ] Fetch an User
- [ ] Fetch list of User:
  - [ ] According to User
  - [ ] According to number
  - [ ] According to specific characteristic

:rocket: Planet milestone will already be implemented.
